ARG GO_IMAGE=docker.io/library/golang:1.24.13-bookworm@sha256:1a6d4452c65dea36aac2e2d606b01b4a029ec90cc1ae53890540ce6173ea77ac
ARG SWIFT_IMAGE=docker.io/library/swift:6.3.3@sha256:56ef1be2c1ca36f4c52440357dc1fcdfdb5e113587134fcadeef57c225c71b54

FROM ${GO_IMAGE} AS orchard-go-build
WORKDIR /source
COPY . .
RUN test "$(go env GOOS)" = linux \
    && CGO_ENABLED=0 GOOS=linux go build -trimpath -buildvcs=false -o /out/orchard ./cmd/orchard

FROM ${SWIFT_IMAGE} AS orchard-assets-build
WORKDIR /source
COPY . .
RUN test "$(uname -s)" = Linux \
    && swift build \
        --package-path tools/asset-compiler \
        --configuration release \
        --disable-automatic-resolution \
    && install -m 0755 tools/asset-compiler/.build/release/orchard-assets /out/orchard-assets

FROM ${SWIFT_IMAGE} AS orchard-runtime
RUN groupadd --gid 10001 orchard \
    && useradd --uid 10001 --gid orchard --home-dir /var/lib/orchard/home --no-create-home --shell /usr/sbin/nologin orchard \
    && install -d -o orchard -g orchard -m 0700 /var/lib/orchard \
    && install -d -o orchard -g orchard -m 0755 /workspace

COPY --from=orchard-go-build /out/orchard /usr/local/bin/orchard
COPY --from=orchard-assets-build /out/orchard-assets /usr/local/bin/orchard-assets
COPY packaging/container-entrypoint /usr/local/bin/orchard-container-entrypoint

ENV ORCHARD_STATE_ROOT=/var/lib/orchard \
    HOME=/var/lib/orchard/home \
    XDG_CONFIG_HOME=/var/lib/orchard/config \
    XDG_DATA_HOME=/var/lib/orchard/data \
    XDG_CACHE_HOME=/var/lib/orchard/cache \
    XDG_STATE_HOME=/var/lib/orchard/state

USER 10001:10001
WORKDIR /workspace
VOLUME ["/var/lib/orchard"]
ENTRYPOINT ["/usr/local/bin/orchard-container-entrypoint"]
CMD ["orchard", "version"]
