#!/bin/sh
set -eu

umask 077

state_root=${ORCHARD_STATE_ROOT:-/var/lib/orchard}
case $state_root in
  /*) ;;
  *)
    printf '%s\n' "ORCHARD_STATE_ROOT must be an absolute path." >&2
    exit 2
    ;;
esac
if [ "$state_root" = / ]; then
  printf '%s\n' "ORCHARD_STATE_ROOT must be a dedicated directory, not /." >&2
  exit 2
fi

HOME=$state_root/home
XDG_CONFIG_HOME=$state_root/config
XDG_DATA_HOME=$state_root/data
XDG_CACHE_HOME=$state_root/cache
XDG_STATE_HOME=$state_root/state
export HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_CACHE_HOME XDG_STATE_HOME

mkdir -p -- "$state_root" "$HOME" "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_CACHE_HOME" "$XDG_STATE_HOME"
chmod 0700 "$state_root" "$HOME" "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_CACHE_HOME" "$XDG_STATE_HOME"

if [ "$#" -eq 0 ]; then
  set -- orchard version
fi
exec "$@"
